name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
      
    - name: NPM install
      run: npm ci
      working-directory: "./src/TeamCityTheatre.Web"
      
    - name: NPM build
      run: npm run build
      working-directory: "./src/TeamCityTheatre.Web"
      
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: "./src/TeamCityTheatre.Web"
